apiVersion: v1
kind: Service
metadata:
  name: notification-redis
  namespace: kubesphere-alerting-system
  labels:
    app: notification
    tier: redis
    version: v0.1.0
spec:
  selector:
    app: notification
    tier: redis
  ports:
  - name: tcp
    protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-redis-pvc
  namespace: kubesphere-alerting-system
  labels:
    app: notification
    tier: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: notification-redis-deployment
  namespace: kubesphere-alerting-system
  labels:
    app: notification
    tier: redis
    version: v0.1.0
spec:
  selector:
    matchLabels:
      app: notification
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notification
        tier: redis
        version: v0.1.0
    spec:
      containers:
      - name: notification-redis
        image: redis:4.0
        imagePullPolicy: IfNotPresent
        command: ["redis-server"]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: notification-redis-pvc
